corrected error that caused consul misbahave after cloudormation update; moved fabio to nomad client node

diff --git a/consul-server/consul-infrastructure.yaml b/consul-server/consul-infrastructure.yaml
--- a/consul-server/consul-infrastructure.yaml
+++ b/consul-server/consul-infrastructure.yaml
@@ -15,10 +15,6 @@ Parameters:
       - 5
       - 7
     Description: Number of member instances to launch in your Consul cluster
-  pMaxCapacity:
-    Type: Number
-    Default: 5
-    Description: Maximal number of member instances to launch in your Consul cluster
   pInstanceType:
     Description: The EC2 instance type
     Type: String
@@ -109,8 +105,23 @@ Rules:
         AssertDescription: All subnets must in the VPC
 
 
+Mappings:
+  # represents information about desired and max capacity of members auscaling group
+  # its even because there is always one node with leader autoscaling group
+  mMember:
+    '3':
+      "desiredCapacity": 2
+      "maxCapacity": 4
+    '5':
+      "desiredCapacity": 4
+      "maxCapacity": 6
+    '7':
+      "desiredCapacity": 6
+      "maxCapacity": 8
+
+
 Resources:
-  rConsulMemberLaunchConfiguration:
+  rConsulBootstrapMemberLaunchConfiguration:
     Type: AWS::AutoScaling::LaunchConfiguration
     Metadata:
       AWS::CloudFormation::Init:
@@ -306,6 +317,304 @@ Resources:
               content: !Sub |
                 [cfn-auto-reloader-hook]
                 triggers=post.update
+                path=Resources.rConsulBootstrapMemberLaunchConfiguration.Metadata.AWS::CloudFormation::Init
+                action=/opt/aws/bin/cfn-init -v --stack ${AWS::StackName} --resource rConsulBootstrapMemberLaunchConfiguration --region ${AWS::Region}
+                runas=root
+          services:
+            sysvinit:
+              cfn-hup:
+                enabled: true
+                ensureRunning: true
+                files:
+                  - /etc/cfn/cfn-hup.conf
+                  - /etc/cfn/hooks.d/cfn-auto-reloader.conf
+              consul-server:
+                enabled: true
+                ensureRunning: true
+                files:
+                  - /etc/init.d/consul-server
+                  - /etc/consul.d/server/config.json
+    Properties:
+      IamInstanceProfile: !ImportValue
+        Fn::Sub: "${pConsulIAMStack}-ConsulServerMemberInstanceProfile"
+      ImageId: !Ref pClusterMemberAmiId
+      InstanceMonitoring: false
+      InstanceType: !Ref pInstanceType
+      KeyName: !Ref pKeyName
+      SecurityGroups:
+        - !Ref rSSHAccessSecurityGroup
+        - !Ref rConsulClusterSecurityGroup
+        - !Ref rConsulRPCAndGossipSecurityGroup
+      UserData:
+        Fn::Base64: !Sub |
+          #!/bin/bash
+          yum install -y \
+              aws-cfn-bootstrap \
+              unzip \
+              wget
+
+          function error_exit {
+            /opt/aws/bin/cfn-signal \
+                --success false \
+                --reason "$1 - look on /var/log" \
+                --stack ${AWS::StackName} \
+                --resource rConsulBootstrapMemberAutoScalingGroup \
+                --region ${AWS::Region}
+            exit 1
+          }
+
+          trap 'error_exit "Line no: $LINENO"' ERR
+
+          /opt/aws/bin/cfn-init \
+              --stack ${AWS::StackName} \
+              --resource rConsulBootstrapMemberLaunchConfiguration \
+              --region ${AWS::Region} || error_exit 'Error during initialization script'
+
+          IP=$(ip addr show dev eth0|awk '/inet /{print $2}'|cut -d/ -f1)
+          NEXT_WAIT_TIME=0
+          OTHER_MEMBERS_ONLINE=$(echo "$(curl -s http://localhost:8500/v1/status/peers | grep -c $IP:)")
+          while [ "$OTHER_MEMBERS_ONLINE" -eq "0" ] && [ $NEXT_WAIT_TIME -le 30 ]; do
+            echo "Waiting for consul"
+            sleep $(( NEXT_WAIT_TIME++ ))
+            OTHER_MEMBERS_ONLINE=$(echo "$(curl -s http://localhost:8500/v1/status/peers | grep -c $IP:)")
+          done
+
+          if [ "$OTHER_MEMBERS_ONLINE" -eq "0" ]; then
+            error_exit 'timeout occurred during waiting for consul servers'
+          fi
+
+          /opt/aws/bin/cfn-signal --success true \
+              --stack ${AWS::StackName} \
+              --resource rConsulBootstrapMemberAutoScalingGroup \
+              --region ${AWS::Region}
+
+
+  rConsulBootstrapMemberAutoScalingGroup:
+    Type: AWS::AutoScaling::AutoScalingGroup
+    Properties:
+      DesiredCapacity: 1
+      HealthCheckGracePeriod: 5
+      HealthCheckType: EC2
+      LaunchConfigurationName: !Ref rConsulBootstrapMemberLaunchConfiguration
+      LoadBalancerNames:
+        - !Ref rConsulLoadBalancer
+      MaxSize: 2
+      MinSize: 0
+      Tags:
+        - Key: Name
+          Value: !Sub "${pResourceNamePrefix}-leader-asg"
+          PropagateAtLaunch: true
+        - Key: !Ref pConsulClusterTagName
+          Value: !Ref pConsulClusterTagMemberValue
+          PropagateAtLaunch: true
+      VPCZoneIdentifier: !Ref "pSubnetIds"
+    CreationPolicy:
+      ResourceSignal:
+        Timeout: PT10M
+    UpdatePolicy:
+      AutoScalingRollingUpdate:
+        MaxBatchSize: 2
+        MinInstancesInService: 1
+        PauseTime: PT10M
+        WaitOnResourceSignals: true
+
+
+
+  rConsulMemberLaunchConfiguration:
+    Type: AWS::AutoScaling::LaunchConfiguration
+    Metadata:
+      AWS::CloudFormation::Init:
+        config:
+          commands:
+            01_install_consul:
+              command: !Sub |
+                #!/bin/bash
+                mkdir /tmp/bin
+                cd /tmp/bin
+                wget https://releases.hashicorp.com/consul/${pConsulVersion}/consul_${pConsulVersion}_linux_amd64.zip
+                wget https://releases.hashicorp.com/consul/${pConsulVersion}/consul_${pConsulVersion}_web_ui.zip
+                unzip consul_${pConsulVersion}_web_ui.zip
+                unzip consul_${pConsulVersion}_linux_amd64.zip
+                rm -f ./*.zip
+
+                mkdir -p /var/consul/data
+                mkdir -p /var/consul/www
+                mkdir -p /home/consul
+
+                useradd -s /bin/false -d /home/consul -r consul
+                chown -R consul /home/consul
+                chown -R consul /var/consul
+
+                mkdir -p /etc/consul.d/
+                mv consul /usr/local/bin/
+                chmod 755 /usr/local/bin/consul
+                mv index.html /var/consul/www/
+                mv static/ /var/consul/www/
+
+                # Add consul user to sudoers and disable tty
+                echo "consul ALL=(ALL) NOPASSWD:ALL" >> /etc/sudoers
+                echo "Defaults:%consul !requiretty" >> /etc/sudoers
+                echo "Defaults:consul !requiretty" >> /etc/sudoers
+          files:
+            /etc/consul.d/server/config.json:
+              content: !Sub |
+                {
+                  "log_level": "INFO",
+                  "datacenter": "${AWS::Region}",
+                  "server": true,
+                  "disable_update_check": true,
+                  "data_dir": "/var/consul/data",
+                  "dns_config": {
+                    "allow_stale": true,
+                    "max_stale": "3s",
+                    "node_ttl": "1m"
+                  },
+                  "skip_leave_on_interrupt": false,
+                  "leave_on_terminate": true
+                }
+              mode: '000444'
+              owner: root
+              group: root
+            /etc/init.d/consul-server:
+              content: !Sub |
+                #!/bin/bash
+                # consul-server daemon
+                # chkconfig: 345 20 80
+                # description: consul-server daemon
+                # processname: consul-server
+
+                DAEMON=/usr/local/bin/consul
+                DAEMON_USER=consul
+
+                SHUTDOWN_WAIT=20
+
+                NAME=consul-server
+                DESC="Consul Server Member"
+                PIDFILE=/var/run/$NAME.pid
+                LOGFILE=/var/log/$NAME.log
+                SCRIPTNAME=/etc/init.d/$NAME
+                DATACENTER="${AWS::Region}"
+
+                ADVERTISE_IP=$(/sbin/ifconfig eth0 | grep 'inet addr:' | cut -d: -f2 | awk '{ print $1}')
+
+                DAEMON_START_OPTS="agent \
+                    -domain 'consul.' \
+                    -advertise $ADVERTISE_IP \
+                    -ui \
+                    -server \
+                    -datacenter $DATACENTER \
+                    -client 0.0.0.0 \
+                    -data-dir /var/consul/data \
+                    -ui-dir /var/consul/www \
+                    -config-file /etc/consul.d/server/config.json \
+                    -rejoin -retry-join-ec2-tag-key ${pConsulClusterTagName} \
+                    -retry-join-ec2-tag-value ${pConsulClusterTagMemberValue} \
+                    -retry-join-ec2-region ${AWS::Region}"
+
+                DAEMON_STOP_OPTS="leave"
+
+                function daemon_pid {
+                  cat $PIDFILE 2> /dev/null
+                }
+
+                function start {
+                  pid=$(daemon_pid)
+                    if [ -n "$pid" ]
+                    then
+                      echo "$NAME is already running (pid: $pid)"
+                    else
+                      echo "Starting $NAME"
+                      ulimit -n 100000
+                      umask 007
+                      touch $LOGFILE
+                      chmod 0644 $LOGFILE
+                      PID=$(/bin/su -p -s /bin/sh -m $DAEMON_USER -c "$DAEMON $DAEMON_START_OPTS" > $LOGFILE 2>&1 & echo $!)
+                      if [ -z $PID ]; then
+                          printf "%s\n" "Fail"
+                      else
+                          echo $PID > $PIDFILE
+                          printf "%s\n" "OK"
+                      fi
+                    fi
+
+                    return 0
+                }
+
+                function status {
+                  pid=$(daemon_pid)
+                  if [ -n "$pid" ]
+                  then
+                    echo "$NAME is running with pid: $pid"
+                  else
+                    echo "$NAME is not running"
+                  fi
+                }
+
+                function stop {
+                  pid=$(daemon_pid)
+                    if [ -n "$pid" ]
+                    then
+                      echo "Stopping $NAME"
+                      /bin/su -p -s /bin/sh -m $DAEMON_USER -c "$DAEMON $DAEMON_STOP_OPTS"
+
+                      kwait=$SHUTDOWN_WAIT
+                      count=0;
+                      until [ "$(ps -p $pid | grep -c $pid)" = '0' ] || [[ $count -gt $kwait ]]
+                      do
+                        echo -n -e "\nwaiting for processes to exit";
+                        sleep 1
+                        count=$count+1;
+                      done
+
+                      if [[ $count -gt $kwait ]]; then
+                        echo -n -e "\nkilling processes which didn't stop after $SHUTDOWN_WAIT seconds"
+                        kill -9 $pid
+                      fi
+                      rm -f $PIDFILE
+                      echo "Stopped"
+                    else
+                      echo "$NAME is not running"
+                    fi
+
+                    return 0
+                }
+
+                case "$1" in
+                start)
+                  start
+                  status
+                ;;
+                status)
+                  status
+                ;;
+                stop)
+                  stop
+                ;;
+
+                restart)
+                  stop
+                  start
+                ;;
+
+                *)
+                  echo "Usage: $0 {status|start|stop|restart}"
+                  exit 1
+                esac
+              mode: '000755'
+              owner: root
+              group: root
+            /etc/cfn/cfn-hup.conf:
+              content: !Sub |
+                [main]
+                stack = ${AWS::StackId}
+                region = ${AWS::Region}
+              mode: '000400'
+              owner: root
+              group: root
+            /etc/cfn/hooks.d/cfn-auto-reloader.conf:
+              content: !Sub |
+                [cfn-auto-reloader-hook]
+                triggers=post.update
                 path=Resources.rConsulMemberLaunchConfiguration.Metadata.AWS::CloudFormation::Init
                 action=/opt/aws/bin/cfn-init -v --stack ${AWS::StackName} --resource rConsulMemberLaunchConfiguration --region ${AWS::Region}
                 runas=root
@@ -334,7 +643,6 @@ Resources:
         - !Ref rSSHAccessSecurityGroup
         - !Ref rConsulClusterSecurityGroup
         - !Ref rConsulRPCAndGossipSecurityGroup
-        - !Ref rConsulHTTPSecurityGroup
       UserData:
         Fn::Base64: !Sub |
           #!/bin/bash
@@ -360,19 +668,6 @@ Resources:
               --resource rConsulMemberLaunchConfiguration \
               --region ${AWS::Region} || error_exit 'Error during initialization script'
 
-          IP=$(ip addr show dev eth0|awk '/inet /{print $2}'|cut -d/ -f1)
-          NEXT_WAIT_TIME=0
-          OTHER_MEMBERS_ONLINE=$(echo "$(curl -s http://localhost:8500/v1/status/peers | grep -c $IP:)")
-          while [ "$OTHER_MEMBERS_ONLINE" -eq "0" ] && [ $NEXT_WAIT_TIME -le 20 ]; do
-            echo "Waiting for consul"
-            sleep $(( NEXT_WAIT_TIME++ ))
-            OTHER_MEMBERS_ONLINE=$(echo "$(curl -s http://localhost:8500/v1/status/peers | grep -c $IP:)")
-          done
-
-          if [ "$OTHER_MEMBERS_ONLINE" -eq "0" ]; then
-            error_exit 'timeout occurred during waiting for consul servers'
-          fi
-
           /opt/aws/bin/cfn-signal --success true \
               --stack ${AWS::StackName} \
               --resource rConsulMemberAutoScalingGroup \
@@ -382,13 +677,13 @@ Resources:
   rConsulMemberAutoScalingGroup:
     Type: AWS::AutoScaling::AutoScalingGroup
     Properties:
-      DesiredCapacity: !Ref pDesiredCapacity
+      DesiredCapacity: !FindInMap [ mMember, !Ref pDesiredCapacity, 'desiredCapacity' ]
       HealthCheckGracePeriod: 5
-      HealthCheckType: ELB
+      HealthCheckType: EC2
       LaunchConfigurationName: !Ref rConsulMemberLaunchConfiguration
       LoadBalancerNames:
         - !Ref rConsulLoadBalancer
-      MaxSize: !Ref pMaxCapacity
+      MaxSize: !FindInMap [ mMember, !Ref pDesiredCapacity, 'maxCapacity' ]
       MinSize: 0
       Tags:
         - Key: Name
@@ -403,6 +698,7 @@ Resources:
         Timeout: PT10M
     UpdatePolicy:
       AutoScalingRollingUpdate:
+        MaxBatchSize: 2
         MinInstancesInService: 1
         PauseTime: PT10M
         WaitOnResourceSignals: true
@@ -451,6 +747,10 @@ Resources:
           IpProtocol: TCP
           ToPort: 8400
         - SourceSecurityGroupId: !Ref rConsulClusterSecurityGroup
+          FromPort: 8500
+          IpProtocol: TCP
+          ToPort: 8500
+        - SourceSecurityGroupId: !Ref rConsulClusterSecurityGroup
           FromPort: 8600
           IpProtocol: TCP
           ToPort: 8600
@@ -465,21 +765,6 @@ Resources:
       Tags:
         - Key: Name
           Value: !Sub "${pResourceNamePrefix}-consul-gossip-sg"
-      VpcId: !Ref pVpcId
-
-
-  rConsulHTTPSecurityGroup:
-    Type: AWS::EC2::SecurityGroup
-    Properties:
-      GroupDescription: Allows gossips and rpc calls among consul cluster members
-      SecurityGroupIngress:
-        - SourceSecurityGroupId: !Ref rConsulClusterSecurityGroup
-          FromPort: 8500
-          IpProtocol: TCP
-          ToPort: 8500
-      Tags:
-        - Key: Name
-          Value: !Sub "${pResourceNamePrefix}-consul-http-sg"
       VpcId: !Ref pVpcId
 
 
@@ -500,6 +785,10 @@ Resources:
           FromPort: 8400
           IpProtocol: TCP
           ToPort: 8400
+        - CidrIp: !Ref pHTTPAccessCIDR
+          FromPort: 8500
+          IpProtocol: TCP
+          ToPort: 8500
         - CidrIp: !Ref pHTTPAccessCIDR
           FromPort: 8300
           IpProtocol: UDP
@@ -531,6 +820,9 @@ Resources:
           Protocol: TCP
         - LoadBalancerPort: '8400'
           InstancePort: '8400'
+          Protocol: TCP
+        - LoadBalancerPort: '8500'
+          InstancePort: '8500'
           Protocol: TCP
         - LoadBalancerPort: '8301'
           InstancePort: '8301'
